[package]
name = "reedline"
version = "0.1.0"
authors = ["Jonathan Turner <jonathan.d.turner@gmail.com>"]
edition = "2018"
description = "A readline-like crate for CLI text input"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = true

[[bin]]
name = "reedline"
path = "src/main.rs"

[dependencies]
crossterm = { version = "0.19.0", features = ["serde"] } 
unicode-segmentation = "1.7.1"
chrono = "0.4.19"
unicode-width = "0.1.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
clipboard = { version = "0.5.0", optional = true }

[dev-dependencies]
tempfile = "3.2.0"

[features]
system_clipboard = ["clipboard"]
